apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic
  namespace: default
data:
  dyn-conf.yml: |
    http:
      routers:
        mstdn:
          entryPoints:
            - "websecure"
          rule: "Host(`mstdn.kernel-panic.lol`)"
          tls:
            certResolver: letsencrypt
          service: mstdn

        rpki:
          entryPoints:
            - "websecure"
          rule: "Host(`rpki.as215855.net`)"
          tls:
            certResolver: letsencrypt
          service: rpki

        authentik:
          entryPoints:
            - "websecure"
          rule: "Host(`authentik.linuxburken.se`)"
          tls:
            certResolver: letsencrypt
          service: authentik

      services:
        mstdn:
          loadBalancer:
            servers:
            - url: "https://192.168.100.33"

        rpki:
          loadBalancer:
            servers:
              - url: "http://192.168.100.43:8323/"

        authentik:
          loadBalancer:
            servers:
            - url: "https://192.168.201.200"
